client/eslint-rules/no-relative-component-imports.js, client/eslint.config.js, client/src/components/header/Avatar.tsx, client/src/components/header/Header.tsx, client/src/components/header/HeaderLower.tsx, client/src/components/header/HeaderUpper.tsx, client/src/components/header/Logo.tsx, client/src/components/header/ProfileBlock.tsx, client/src/components/header/QuickLinks.tsx, client/src/components/table/filters/ColumnFilterSelect.tsx, client/src/components/table/pagination/PaginationControls.tsx, client/src/components/table/tables/DemonstrationTable.tsx, client/vite.config.ts, server/eslint-rules/validate-graphql-typescript-match.js, server/eslint.config.js, server/src/auth/auth.util.ts, server/src/model/permission/permission.ts
Replaces `export default` with `export {namedVariable}` and fixes a couple of linting rules in the server to get these ready for CI/CD (both just unused vars)
=> Replace default exports with named exports

client/eslint.config.js, client/src/components/auth/AuthButtons.tsx, client/src/components/button/ErrorButton.tsx, client/src/components/button/PrimaryButton.tsx, client/src/components/button/TertiaryButton.tsx, client/src/components/table/tables/DemonstrationTable.tsx, client/src/layout/PrimaryLayout.tsx, client/src/layout/SideNav.test.tsx, client/src/layout/SideNav.tsx
The prettier config setting for `trailingComma: es5` was at odds with our `comma-dangle` config as imports need to be specifically declared as being expected to have a trailing comma where I thought this was covered by the `objects` key before.
Formatted some files while kicking the tires
=> Eslint: Fix comma-dangle config

client/index.html, client/package-lock.json, client/package.json, client/src/components/header/Header.test.tsx, client/src/hooks/useUserOperations.test.tsx, client/src/hooks/useUserOperations.ts, client/src/mock-data/index.test.ts, client/src/mock-data/index.ts, client/src/mock-data/userMocks.ts, client/src/pages/debug/TestHooks.tsx, client/src/router/DemosApolloProvider.tsx, client/src/router/DemosRouter.tsx, client/tsconfig.json, client/vite.config.ts, server/package.json, server/src/types.ts, server/tsconfig.json
This change adds support for conditionally using Apollo's `MockedProvider` versus the main `ApolloProvider` depending on environment and a new environment variable: `VITE_USE_MOCKS`
- Test: Always use mocks
- Dev: Use mocks if VITE_USE_MOCKS is true
- Prod: Never use mocks
=> Demos 295: Conditional MockedProvider / ApolloProvider

server/.env.example, server/src/seeder.ts
Added ALLOW_SEED to the .env.example that must be set to true to use the seed functions.
Also added a default connection string to the devcontainer postgres.
=> DEMOS-301: Add ALLOW_SEED and a connection string for local development

client/src/components/table/tables/DemonstrationTable.tsx
This PR implements the default sorting behavior for both **My Demonstrations** and **All Demonstrations** tabs based on user feedback.
- Applied default sorting state in `DemonstrationTable.tsx`:
- Primary sort: `State/Territory (stateId)` ascending
- Secondary sort: `Title (title)` ascending
```ts
const [sorting, setSorting] = React.useState<SortingState>([
{ id: "stateId", desc: false },
{ id: "title", desc: false },
]);
=> DEMOS-253 - Updates Demos sort order

client/src/components/table/columns/DemonstrationColumns.tsx, client/src/components/table/tables/DemonstrationTable.test.tsx
**Summary**  
This PR adds a new "View" button to each row in the Demonstrations table, allowing users to navigate directly to the detail page of a specific demonstration.
---
**Changes Made**
- Added a new `viewDetails` column in `DemonstrationColumns.tsx` using the shared `SecondaryButton` component.
- Clicking the button routes the user to `/demonstrations/:id`.
- Disabled sorting for this column to maintain UI clarity.
---
**Tests**
- Updated `DemonstrationTable.test.tsx` to verify the presence and label of the "View" button in each parent row.
- All 6 tests pass:
- Validates row expansion
- Validates filtering logic
- Confirms button rendering and accessibility
**Run Command**
```bash
npx vitest run src/components/table/tables/DemonstrationTable.test.tsx
=> DEMOS-46 - Adds View details button

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .devcontainer/docker-compose.yml, .devcontainer/post_create.sh, .gitignore, server/.env.example, server/localstack/localstack.sh, server/package-lock.json, server/package.json, server/src/auth/auth.util.ts, server/src/model/demonstrationStatus/demonstrationStatusSchema.ts, server/src/model/state/stateSchema.ts, server/src/model/user/userSchema.ts, server/src/server.ts
This PR is essentially two features in one: updating our local development environment to use `localstack` for the server, and adding support to the server Lambda to get the authentication details from SecretsManager and use them to talk to the database. I'm writing a bit more here just for context.
This changes the devcontainer setup in a few ways.
- Installs the `awscli` package, which is used by the `localstack` setup.
- Removes port forwarding from the actual devcontainer setup and moves it to the Docker compose.
- Adds a proper post-create script, needed for AWS configuration. In that script, we set up the `awscli` profile for `localstack` and alias the `aws` command to include the endpoint (for some reason, none of the other ways of setting that up are honored).
- Adds a setting …
=> DEMOS-423-add-lambda-secretsmanager-items

deployment/build.js, deployment/stacks/api.ts, deployment/stacks/core.ts, deployment/stacks/ui.ts
This avoids conflicts between multiple environments in the same account.
None of these outputs are currently used by the CDK code, so there are no conflicts to work through
=> DEMOS-481: Rename CfnOutputs to include stage name

server/src/model/demonstration/demonstration.prisma, server/src/model/demonstration/demonstrationResolvers.ts, server/src/model/demonstration/demonstrationSchema.ts, server/src/model/migrations/20250623155458_init_baseline/migration.sql, server/src/model/migrations/20250623155513_add_history_triggers/migration.sql, server/src/seeder.ts
This PR adds a project officer to the demonstration.  Also fixes a missing arg (id) in the update demonstration mutation.
Tested with the following operations:
```
query ExampleQuery {
demonstrations {
projectOfficer {
id
username
email
fullName
displayName
}
id
name
createdAt
demonstrationStatus {
id
}
users {
id
username
}
}  
}
query ExampleQuery($updateDemonstrationId: ID!) {
demonstration(id: $updateDemonstrationId) {
projectOfficer {
id
username
email
fullName
displayName
}
id
name  
}
}
mutation DeleteDemonstration($deleteDemonstrationId: ID!) {
deleteDemonstration(id: $deleteDemonstrationId) {
id
}
}
mutation AddDemonstration($addDemonstrationInput2: AddDemonstrationInput!) {
addDemonstration(input: $addDemonstrationInput2) {
id
}
}
mutation …
```
=> Demos 303 - Add project officer to demonstrations and fix a few gql bugs

pipelines/lib/vars/kubeBlock.groovy, pipelines/lib/vars/snykScan.groovy
This adds a new library function for running Snyk scans in the Jenkins pipelines. 
This PR is to add the functionality itself, and then a second PR will be opened to use the function within the pipelines. (The library is mapped to the `main` branch, so a single PR creating the function and using it can't be added together without ad hoc changes that I'd prefer to stay away from)
=> DEMOS-564: Add synkScan jenkins library function

server/src/model/demonstration/demonstrationSchema.ts, server/src/model/demonstrationStatus/demonstrationStatusSchema.ts, server/src/model/document/documentSchema.ts, server/src/model/documentType/documentTypeSchema.ts, server/src/model/event/eventSchema.ts, server/src/model/modification/modificationSchema.ts, server/src/model/modificationStatus/modificationStatusSchema.ts, server/src/model/permission/permissionSchema.ts, server/src/model/role/roleSchema.ts, server/src/model/state/stateSchema.ts, server/src/model/user/userSchema.ts
Very simple PR that just changes the query returns in the GraphQL schemas to use `[Thing!]!` instead of `[Thing]!`. This is a small tweak, but makes the results more consistent with the other types throughout the system. `[Thing]!` means that an array is always returned, but that the elements can either be `Thing` or `null`. `[Thing!]!` means that the array must have only non-null elements. Both allow for empty arrays, to be clear.
Unless there's an actual reason to expect / return null elements from a query (i.e. the null values communicate some meaning), everything I've seen indicates the `[Thing!]!` type is more appropriate in GQL.
=> DEMOS-577-gql-list-return-types

lambda_authorizer/index.mjs
Previously, the authorizer would throw an error if the JWT was invalid. This would prevent the user from accessing the API but would result in a 500 response to the client. This change updates the response to always use a Deny policy so a proper 403 response is returned for all issues.
=> DEMOS-604: Handle authorizer errors and deny request

client/package.json, client/tsconfig.json, server/package.json
DEMOS-598: Imports only the types from the server rather than the whole thing, also get the `constants.ts` file
=> DEMOS-598: Import only types from server

client/src/components/header/DefaultHeaderLower.test.tsx, client/src/components/header/DefaultHeaderLower.tsx, client/src/components/input/select/SelectCMCSDivision.test.tsx, client/src/components/input/select/SelectCMCSDivision.tsx, client/src/components/input/select/SelectSignatureLevel.test.tsx, client/src/components/input/select/SelectSignatureLevel.tsx, client/src/components/modal/DemonstrationModal.test.tsx, client/src/components/modal/DemonstrationModal.tsx
DEMOS-288 - adds the `CMCSDivision` and `SignatureLevel` dropdown fields to the `DemonstrationModal`
**Actual**
**Mocks**
=> DEMOS-288: Add fields to DemonstrationModal

server/package.json, server/src/model/document/documentResolvers.ts, server/src/model/document/documentSchema.ts
This PR addresses a bug discovered in the Document resolver where certain required fields were absent from the resolver code. It also fixes the `deleteDocuments` mutator to correctly return the count of deleted records (it does not return a list of IDs).
This also changes `package.json` so that in the future, running `npm run build` or `npm run build:ci` will properly give a non-zero error code if `tsc` fails. This will ensure that at least after merge, an error will be raised (one was not presently). @cms-jesse is going to add a PR check that runs the build as well.
In just cleaning up, I pulled out the check for whether a bundle type was implemented or not, since they're all implemented now.
I validated that this worked by running it locally and using the mutators to do a number of …
=> DEMOS-699-fix-document-resolver

deployment/lib/guardDutyS3.ts, deployment/lib/wait.ts, deployment/stacks/bootstrap.ts
This change adds a new lambda at the account level that can be used by any stack to wait for a certain number of seconds. The "wait" resource can set a dependency to start the timer, then other resources can add the wait as a dependency so they aren't created until the timer is up. The number of seconds to wait can be set within the stack up to 5 minutes.
This is used along with the guard duty S3 scanning in order to avoid the race condition between it and the role creation
=> DEMOS-711: Add a delay lambda and use it for guard duty

client/src/components/dialog/EditContactDialog.test.tsx, client/src/components/dialog/EditContactDialog.tsx, client/src/components/dialog/index.ts, client/src/components/table/tables/ContactsTable.test.tsx, client/src/components/table/tables/ContactsTable.tsx, client/src/components/table/tables/ContactsTableDemo.tsx, client/src/pages/DemonstrationDetail/DemonstrationTab.tsx
https://jiraent.cms.gov/browse/DEMOS-547
This PR introduces a new EditContactDialog modal for updating a contact’s type while keeping name and email fields read-only for security. The dialog follows the existing `BaseDialog` pattern, includes clear validation, helper text for disabled fields, cancel confirmation, and toast notifications for user guidance. Supported contact types include Primary/Secondary Project Officer, State Representative, and Subject Matter Expert.
Integration updates include adding edit functionality to ContactsTable (with validation for single-row selection and toast feedback), wiring up contact updates in DemonstrationTab, and exporting the dialog via `index.ts`. A full test suite covers rendering, validation, submission, cancel behavior, and field restrictions to …
=> DEMOS-547 Edit Contacts Dialog

client/src/components/dialog/RemoveContactDialog.tsx, client/src/components/dialog/index.ts, client/src/components/table/tables/ContactsTable.test.tsx, client/src/components/table/tables/ContactsTable.tsx, client/src/components/table/tables/ContactsTableDemo.tsx, client/src/pages/DemonstrationDetail/DemonstrationTab.tsx, client/vitest.setup.ts
https://jiraent.cms.gov/browse/DEMOS-559
This PR implements a confirmation dialog for removing contacts from the contacts table to prevent accidental deletions. The changes include creating a new `RemoveContactDialog` component that appears when users click the "Remove Contact" button, requiring explicit confirmation before deletion occurs.
The implementation also fixes a test environment issue where HTML dialog elements weren't properly mocked in Vitest. The dialog mocks now correctly set the `open` property when `showModal()` is called, ensuring that dialog-based components can be properly tested. All existing tests continue to pass with the new confirmation workflow.
=> DEMOS-559 Removes Contacts from contact list

deployment/demosctl/commands/addCloudfrontRedirect.test.ts, deployment/demosctl/commands/addCloudfrontRedirect.ts, deployment/demosctl/commands/buildClient.test.ts, deployment/demosctl/commands/buildClient.ts, deployment/demosctl/commands/buildServer.ts, deployment/demosctl/commands/down.test.ts, deployment/demosctl/commands/down.ts, deployment/demosctl/commands/fullDeploy.test.ts, deployment/demosctl/commands/fullDeploy.ts, deployment/demosctl/commands/getCoreOutputs.test.ts, deployment/demosctl/commands/getCoreOutputs.ts, deployment/demosctl/commands/runMigration.test.ts, deployment/demosctl/commands/runMigration.ts, deployment/demosctl/commands/testMigration.test.ts, deployment/demosctl/commands/testMigration.ts, deployment/demosctl/commands/up.test.ts, deployment/demosctl/commands/up.ts, deployment/demosctl/demosctl.ts, deployment/demosctl/index.ts
Updates the demosctl utility (which is used in the jenkins pipelines) so that the exit codes match the processes the commands run. Previously at the root level, commands were being called, but some exit codes were being ignored. As part of this change, I modified the code to return the exit code and only call process.exit at the top level rather than individually within the functions.
=> DEMOS-811: exit cli with non-zero when scripts error

deployment/stacks/core.test.ts, deployment/stacks/core.ts
This change adds a new VPC Endpoint to that will be used for access to the parameter store. The current use case is for storing info related to DB users, but may be used for other items in the future
=> DEMOS-764: Add systems manager VPC endpoint

pipelines/Jenkinsfile.deploy, pipelines/lib/vars/notifyMigrationError.groovy
This change adds a notification within the deployment pipeline if the migrations fail
Since this pipeline is only run after code is merged, there are no Jenkins ENVs to get the github username, which is what has been set up to correlate everyone with their slack ID. So this change just gets the commit hash from the latest commit, then queries github to get the username. It will mention that person, plus any slack IDs listed in SLACK_DB_NOTIFICATION_USERS, which is a comma-separated list of ids managed on the Jenkins instance (and currently contains only Tom's ID).
=> DEMOS-919: Send slack notification with mentions if migrations fail

client/src/components/input/select/AutoCompleteSelect.tsx
So this feels more like addressing a symptom of a problem rather than the core issue; i have suspicions we might need some adjustments to this component for 508 testing, as we are using this as a select, but it actually is a text input. Issue is that chrome sees this text input and attempts to autofill it, or provide options based on previously submitted values. Since this search bar is intended to be more of a helper for finding the correct value, ive gone ahead and simply disabled autocomplete. 
The other solutions ive seen proposed for this is to make the select actually contain a hidden select field, which is actually whats used in the form. This seems at the time a bigger refactor than the scope of this ticket, but not entirely sure whats the best way to go with this. 
Nonetheless, …
=> DEMOS-866: prevented autocomplete on search field

client/src/components/dialog/BaseModificationDialog.test.tsx, client/src/components/dialog/BaseModificationDialog.tsx, client/src/hooks/useDemonstration.test.tsx, client/src/hooks/useDemonstration.ts
Implemented context-aware behavior for Amendment and Extension creation dialogs based on user requirements.
- **When creating from landing page**: State field is enabled and user can select any state
- **When creating from within demonstration**: State field is disabled and pre-populated with the demonstration's state value
- **When creating from landing page**: Project Officer field is visible and required
- **When creating from within demonstration**: Project Officer field is hidden (not shown in UI)
- `BaseModificationDialog.tsx` - Added conditional field rendering and state pre-population logic
- `BaseModificationDialog.test.tsx` - Enhanced with comprehensive test coverage for both scenarios
- `useDemonstration.ts` - New hook to fetch detailed demonstration data for form …
=> DEMOS-792 Amendment/Extension Dialog Changes

pipelines/lib/vars/hasChange.groovy, pipelines/lib/vars/notifyMigrationError.groovy
This is the first part of a 2-part PR for skipping unnecessary pipeline stages when a PR is made. This PR has to be split up because the library is always pulled from `main`, so the pipeline changes will throw errors if the library function isn't merged first.
The library function hasChange takes a path and an optional target branch to compare with. If paths are passed as a list, each given path will be checked. The function returns "true" if the git diff contains a matching path. This will be used in the pipelines to conditionally run the stages.
If hasChange is called and the pipeline is not being run as part of a PR, this function will always return true so that no stages are skipped. This is important for the main branches (`main` and `test`)
---
A second commit was also made to …
=>  DEMOS-956: Add jenkins library function hasChange 
